### ISSUE TITLE
Compile server: switch from using JOBE to a Microsoft platform

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#11]
The advantage would be that we could compile C# and, more importantly, VB to latest versions rather than relying on Mono (which, for VB in particular, lags a long way behind current versions of Microsoft languages).

**Comment by scascarini** [comment]
Done although we will want to do further security refinements

**Comment by scascarini** [comment]
take back for adding tests

**Comment by richardpawson** [comment]
Done (anything leftover is in other tickets)
