### ISSUE TITLE
Improve the initial access and log-in experience.

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#114]
### New experience for first visit (not logged in)

You will be presented with a static `Html `page that:

- Explains what Express is and does.
- Explains that you need to be registered either as a Teacher or as a Student. If you already are, then please **log in here.**; if you are not already registered and you log in you won't be able to access any of the system's functionality.

**How to register**
- If you are a **Student**, you need to have an invitation (by email) from a teacher already registered on Express. Just follow the  link in the email the teacher sends you.

- If you are a **Teacher**, and would like to be able to use MetalUp with your students please complete and submit **this form**. There is no charge for this, but you will be asked to submit evidence of your status as a teacher at a school, college, or university. Please note that  this information is manually reviewed and while we _typically_ respond the same day, it can take a few days depending upon our availability. If your application is successful you will be emailed with instructions on how to explore the projects available on MetalpUp.Express, invite students and/or other teacher colleagues to participate, assign projects to students, track their progress, and administer your own organisational and student data. 

(Footnote about privacy policy).

**Comment by scascarini** [comment]
Changed to use new auth-angular library.  This requires some config changes in Auth0 - Need to create an API on Auth0. The client now sends down an access token not the id_token. Need a custom rule on Auth0 to include email address in access token.

**Comment by scascarini** [comment]
With the new auth lib it automatically refreshes the auth token without user interaction.

**Comment by scascarini** [comment]
still to do - improve experience if navigate directly to a page when unauthorised/not registered. currently see blank - should redirect to landing page

**Comment by scascarini** [comment]
complete

**Comment by richardpawson** [comment]
Completed
