### ISSUE TITLE
AsGrid(exampleCells) on Life Task 0 is not working

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#123]

**Comment by scascarini** [comment]
Looking at the HiddenCode file for the task. The '■' seems to have been stripped out.  I suspect it's to do with encoding changes. I fixed by putting the unicode character in as '\u25A0'

**Comment by scascarini** [comment]
Looking at File_Functions.  The file contents are being forced to ASCII. ASCII characters work OK - but unfortunately no ASCII character for 'black box' (FE shows as 'thorn').

**Comment by richardpawson** [comment]
So the trick will be not to embed the char as \u`25A0`, but to add in the char programmatically translated from the hex value.

There is some code to do this [here](https://stackoverflow.com/questions/28141761/c-sharp-character-from-unicode ).

**Comment by richardpawson** [comment]
I don't think that the code in File_Functions which forces the encoding to ASCII is causing the problem, because at that point the intended black box is still represented as ASCII i.e. as six ASCII characters `\u25A0` in a literal string.  It is only in the C# compiler that this string of six ASCII chars is re-interpreted to be a single Unicode character (black box). 

If `File_Functions.ToASCIIonly` was stripping out (or modifying) the `\u25A0` (because it was seen as non-ASCII) then that string `\u25A0` would _not_ appear on the UI when you invoke `Edit Contents As String` on a `File `object (which it does) because those contents have been passed through 'ToASCIIonly` in order to generate the default value for `Edit Contents As String`.

Therefore, please validate that `\u25A0` is still there when you assemble the `Wrapper` (injecting `HiddenCode.cs`) and send it up to the compiler.

**Comment by richardpawson** [comment]
The problem lies _after_ the compile server, in the generation of the Html code. 
For now we will restrict the tasks to using ASCII code only in the output. 
Longer term - when need arises - we will perhaps introduce a new generalised capability to allow tasks to introduce, or at least provide code to invoke, a wider range of graphical output e.g. graphs, images.  I envisage that a `Task` will perhaps have an optional `Rendering` file (presumably JavaScript), which will process ASCII output from the compile server (e.g. as a `CSV`) and that file will process the data and use it to call more powerful graphics capabilities in the client, to put into (perhaps) a Graphical Output pane.
