### ISSUE TITLE
Show Line/Char number for cursor in Code pane header.

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#155]
Our compile server should be (is?) returning the line number for errors - though I haven't seen this coming through to UI. First step in this ticket is to make sure that info is coming through to error message for all supported languages.

This ticket originally called for highlighting of the erroneous line, but Stef points out (see comment below) that this is very fiddly to implement. 
 
Instead - at least for the time being - I am requesting an indicator (e.g. within the code header) showing the Line/CharNo where the cursor currently is. This would have to count the same way as understood by the compile server i.e. distinguish between wrapped lines and new lines.

**Comment by scascarini** [comment]
The line numbers are in the cmpinfo - we filter out from display messages.  They'll be different for each language so we will probably need to create language specific regex to extract.  

Highlighting text in a textarea is a bit fiddly e.g. see 

https://stackoverflow.com/questions/66899473/highlight-specific-words-in-textarea-angular-8
