### ISSUE TITLE
Link navigation leaves angular

### ISSUE THREAD

**Issue by scascarini** [MetalUp/Express#168]
We just change the window location when navigating a a url link! This triggers an angular reload. Use the router.

**Comment by scascarini** [comment]
[https://github.com/NakedObjectsGroup/NakedObjectsFramework/issues/484](url)

**Comment by richardpawson** [comment]
I have tested that I can navigate the link from the Dashboard to a Task view, from within an `incognito ` browser, and it worked fine.
