### ISSUE TITLE
Python type hints - need to make switchable

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#172]
(Update) Decision: this will be made switchable by means of two different Language instances.

- Python
- Python (typed)

When using the former, the use of type hints is _optional_ but they will be accepted.
For any task using the latter, the compile service will be invoked with myPy, enforcing the specification of type hints.

**Comment by scascarini** [comment]
Currently it is switchable for each compile request from the admin server by setting the 'MyPy' compile options. 

Was on by default now off,

**Comment by richardpawson** [comment]
Completed
