### ISSUE TITLE
Error on first compile request

### ISSUE THREAD

**Issue by scascarini** [MetalUp/Express#180]
An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.

**Comment by richardpawson** [comment]
So I can test and close the ticket, please just remind me ... was the error upon first request after a browser refresh, or first request after a server re-build ?
   
   
   
    On 23/03/2023 10:53 GMT Stefano Cascarini ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Assigned #180 to @richardpawson.

**Comment by scascarini** [comment]
server rebuild (it's to do with initialising a static variable)
