### ISSUE TITLE
Can't get Decimal() working in Python

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#185]
I have added these import statements to the standard Wrapper:

```
import decimal
from decimal import Decimal
```

per [documentation]( https://docs.python.org/3/library/decimal.html) 
but trying to use the function - e.g. `Decimal(4)` - (unusually the function does begin upper case) 

I get:

```
temp.py:61:16: error: Name "Decimal" is not defined  [name-defined]
Found 1 error in 1 file (checked 1 source file)
```

I'm wondering if compile server lacks the necessary library? (Though in this case I would have expected a different message).

**Comment by scascarini** [comment]
I think this works (ie I tried and is OK on dev). Did you add the import to the right Python file - ie Python vs Python Typed?

**Comment by richardpawson** [comment]
Problem was that the Task I was using had the Q&A wrapper, not the default one!
