### ISSUE TITLE
Compiler rejecting correct type annotations for tuples

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#201]
This example:

`def foo(la: tuple[int,...], lb: tuple[int,...]) -> tuple[int,...] : return la + lb`

is generating:

`error: Syntax error in type annotation   (15,5)`

Other, simpler expressions involving tuple types also being rejected (with different errors). The above code runs on PyCharm, which is also running MyPy.

I wonder if it is a versioning issue, either of Python or MyPy ? Although according to this source - https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html - the syntax I have used for the tuple types is valid in Python 3.9+

**Comment by scascarini** [comment]
That code compiles OK in a standalone test vs mypy on the compile server.

Is it possible that it's causing a type error somewhere else in the python
wrapper code ?
