### ISSUE TITLE
Error messages from MyPy being truncated (by RegEx Rules?)

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#214]
Example:

`error: Returning Any from function declared to return  (3,3)`

Looking at the message in the console, it is:

`error: Returning Any from function declared to return \"int\"  [no-any-return]`

So the `\" `is probably the cause of the problem _rather than the Regex_  (I think).

**Comment by scascarini** [comment]
This is the regex not matching the extra non \w characters in the error string - something like this matches the whole message

error: .* 

(I've changed in the regex file for typed python)

**Comment by richardpawson** [comment]
I fixed several broken Smoke Tests last night.  One remaining (current) failure is RegEx relating.
   
  
    
   
  
   I think what happened was that you made a change to the RegEx file yesterday - to fix exactly this failure - but you perhaps made the change directly to the File in Dev. This would have been overwritten on the next Dev Build by the Common File. Can you recall the change you made to the RegEx and make it in the common files?
   
  
    
   
  
   It has been a frustrating couple of days with the build, but I feel that what we are doing at the moment is absolutely right and will get better. 
   
  
    
   
  
   Two things I would like to discuss this morning, to do today if possible. (This is in addition to the database copy script from Dev -> Test). 
   
  
    
   
  
   1) I want to get the Common Files Solution brought into the build, so that we know that all those files compile. (This includes a Visual Studio PY project - can that be handled?)
   
  
    
   
  
   2) I want to add unit tests for all those common files. I have written some and can write more. (Again, we need to discuss how unit tests are run on PY project.) I would also like you to write me a minimalist test harness for testing the RegEx rules.  I'm happy to write the actual tests.
   
  
    
   
  
   I need something that will work in all three languages, and test:
   
  
    
   
  
   - An Expression submission against the appropriate RegEx rules. Just run as local unit test.
   
  
   - A Code submission against against the appropriate RegEx rules. Just run as local unit test.
   
  
   - Application of RegEx rules to output from Compile server. I think this one needs to work with the Compile server rather than just be standalone unit test.
   
   
   
  
   Will clarify when we talk.
   
   
   
    On 09/05/2023 17:34 BST Stefano Cascarini ***@***.***> wrote:
    
   
     
    
   
     
    
     
   This is the regex not matching the extra non \w characters in the error string - something like this matches the whole message 
   error: .* 
   (I've changed in the regex file for typed python)

**Comment by richardpawson** [comment]
Completed
