### ISSUE TITLE
Unable to use 'reduce' function for Python compile

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#216]
I have added the required:

`from functools import reduce`

into the default wrapper for Python (and then works correctly in PyCharm) but the compile server is returning error:

NameError: name 'reduce' is not defined

Is another package needed in the compile server?

**Comment by scascarini** [comment]
functools appears to be built in to latest python. 

And seems to be working. Tried on dev 

code : def xor(x:int, y:int) -> int : return (x+y)%2

expression : reduce(xor, [1,2,3,4,5,6])

returns 1

**Comment by scascarini** [comment]
To install  a package on the compile server

d:\home\python3111x64>.\python.exe -m pip install <package>

don't use just 'py' as that uses the path to go to the root python install which is 2.6 rather than our custom 3.11 install

**Comment by richardpawson** [comment]
Seems to be working now
