### ISSUE TITLE
Small change to URLlink to Edit View of File

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#228]
(I'm not sure if this is NOF-general, or Express-specific)

Currently, if URLlink is on a property, then you have the option to:

- Left-Click to go to the URL on the current tab
- Right click to  open the URL on another tab

But if URLlink is on an action then it always opens on the same tab.

I am anyway beginning to think I would _prefer_ that a URL link should _always_ open in a new tab, so you don't use your context in the main system.

So, maybe this should be another configuration option? What's your view, Stef?

**Comment by scascarini** [comment]
There is an option on the UrlLink attribute 'alwaysOpenInNewTab'
