### ISSUE TITLE
Improve log-in, sign-up

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#55]
1. Currently no distinction between **Log-in** and **Sign-up**. Should there be? Can we configure it to have only one?

2. Can we add more Auth0 providers e.g. GitHub, Facebook, LinkedIn, Instagram? And can we eliminate the (confusing) option to log in with own email and password?

3. On Log-in the user should now always be taken to the dashboard.

4. Apparently if you go to `http://express.metalup.or`g (rather than **https**) you are still invited to log in but there, but then get a callback (photo at end of posting).

![image](https://user-images.githubusercontent.com/1838114/192007832-e015e12a-8370-4091-b67e-e825216de455.png)

**Comment by scascarini** [comment]
http on express.metalup.org now redirects to https

**Comment by richardpawson** [comment]
Completed
