### ISSUE TITLE
VB version not working with Run Tests

### ISSUE THREAD

**Issue by richardpawson** [MetalUp/Express#96]
Previously I was getting an error 'unexpected character...'. I traced this to a spurious semi-colon in the client's VB wrapper code, leftover from C# conversion probably (see my check in 3d59731 entitled `...continuation of previous` ).

That error has now gone, but any **Run Test** submission is now giving me:

`Exception has been thrown by the target of an invocation.`  with no further info in the JSON response.

You can test this out with e.g. [Task 62](https://express.metalup.org/task/62)

Note that Paste is (temporarily enabled) so just go to Hint 3 and copy into Functions pane.

**Comment by scascarini** [comment]
The exception is the test failure exception - the tests are failing because IsNot compare the references to contents of the strings.

This works 

 Sub TestFunction(functionName As String, expected As Object, actual As Object, ParamArray args As Object())

        If (Not Display(actual).Equals(Display(expected))) Then
            Console.WriteLine(fail + $"{functionName}({ArgString(args)}) Expected: {Display(expected)}  Actual: {Display(actual)}")
            Throw New TestFailure()
        End If

    End Sub

**Comment by richardpawson** [comment]
OK - that was an error in the translation of the C# wrapper code to VB then.

But why, if it is throwing the TestFailure exception, is the console message showing the test that has failed not appearing ? (If it had, I would have known that the test was failing, though the message might have been puzzling!)

**Comment by scascarini** [comment]
I was not recording stdout when an error was thrown. Updated

**Comment by richardpawson** [comment]
Fixed
